import {MigrationInterface, QueryRunner} from "typeorm";

export class catchup1633260947705 implements MigrationInterface {
    name = 'catchup1633260947705'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."packages" DROP CONSTRAINT "FK_16293605f042acb4078c2a324d2"`);
        await queryRunner.query(`ALTER TABLE "public"."wagons" DROP CONSTRAINT "FK_99c13262873ed08473e66bc4eac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16293605f042acb4078c2a324d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99c13262873ed08473e66bc4ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0c6adf735891a8c59a9fec34b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e1cef4d628456b8e51702fea3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7e11f089a785ffa5f65c9674f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc0d43a83e4083de2db699c644"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4e656a1a641ee344881f50885"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ea0868bf622bc7d2ed503eafe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a875e5b908245d08664422ebd"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP CONSTRAINT "PK_4ef5576fbbbdfcff407d0f3b6ff"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD CONSTRAINT "PK_e4a77c477e29608e7d17d17fb4f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteId"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteStartlocationid"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteEndlocationid"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteEstimatedtime"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteStarttime"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteEndtime"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteCreatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP COLUMN "currenRouteUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_4f81dc12bd5e895ac9475630642"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_9ed4507a1f3ba46e96145275a4b" PRIMARY KEY ("id", "deliveredAtLocationId", "assignToTrainId", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationId"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationType"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationLatitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationLongitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationCanload"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationCanunload"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationCreatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocationUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_9ed4507a1f3ba46e96145275a4b"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_2ead56e1373b6bc109cdc221a92" PRIMARY KEY ("id", "assignToTrainId", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationId"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationType"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationLatitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationLongitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationCanload"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationCanunload"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationCreatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocationUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_2ead56e1373b6bc109cdc221a92"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_e4e363fbbd9abbae5017e04ed29" PRIMARY KEY ("id", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainId"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainType"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainMaxweight"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCangoaboard"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainLatitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainLongitude"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainIsfull"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCreatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_e4e363fbbd9abbae5017e04ed29"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteId"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteStartlocationid"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteEndlocationid"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteEstimatedtime"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteStarttime"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteEndtime"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteCreatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignToTrainCurrenRouteUpdatedat"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocation" integer`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocation" integer`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignedToTrainId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_1469606030def64002bd611d53" ON "public"."packages" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a6e274ac885393d70d64247b0" ON "public"."wagons" ("currentTrainId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ef48e6e3b0eb8f7982df2e781" ON "public"."orders" ("assignedToTrainId") `);
        await queryRunner.query(`ALTER TABLE "public"."packages" ADD CONSTRAINT "FK_1469606030def64002bd611d538" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."wagons" ADD CONSTRAINT "FK_1a6e274ac885393d70d64247b02" FOREIGN KEY ("currentTrainId") REFERENCES "trains"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "FK_5ef48e6e3b0eb8f7982df2e781b" FOREIGN KEY ("assignedToTrainId") REFERENCES "trains"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "FK_5ef48e6e3b0eb8f7982df2e781b"`);
        await queryRunner.query(`ALTER TABLE "public"."wagons" DROP CONSTRAINT "FK_1a6e274ac885393d70d64247b02"`);
        await queryRunner.query(`ALTER TABLE "public"."packages" DROP CONSTRAINT "FK_1469606030def64002bd611d538"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ef48e6e3b0eb8f7982df2e781"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a6e274ac885393d70d64247b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1469606030def64002bd611d53"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "assignedToTrainId"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "deliveredAtLocation"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP COLUMN "pickedUpLocation"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteEndtime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteStarttime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteEstimatedtime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteEndlocationid" integer`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteStartlocationid" integer`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCurrenRouteId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_e4e363fbbd9abbae5017e04ed29" PRIMARY KEY ("id", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainIsfull" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainLongitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainLatitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainCangoaboard" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainMaxweight" numeric`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainType" character varying`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "assignToTrainId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_e4e363fbbd9abbae5017e04ed29"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_2ead56e1373b6bc109cdc221a92" PRIMARY KEY ("id", "assignToTrainId", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationCanunload" boolean`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationCanload" boolean`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationLongitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationLatitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationType" character varying`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "deliveredAtLocationId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_2ead56e1373b6bc109cdc221a92"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_9ed4507a1f3ba46e96145275a4b" PRIMARY KEY ("id", "deliveredAtLocationId", "assignToTrainId", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationCanunload" boolean`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationCanload" boolean`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationLongitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationLatitude" numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationType" character varying`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD "pickedUpLocationId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."orders" DROP CONSTRAINT "PK_9ed4507a1f3ba46e96145275a4b"`);
        await queryRunner.query(`ALTER TABLE "public"."orders" ADD CONSTRAINT "PK_4f81dc12bd5e895ac9475630642" PRIMARY KEY ("id", "pickedUpLocationId", "deliveredAtLocationId", "assignToTrainId", "assignToTrainCurrenRouteId")`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteUpdatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteCreatedat" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteEndtime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteStarttime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteEstimatedtime" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteEndlocationid" integer`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteStartlocationid" integer`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD "currenRouteId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "public"."trains" DROP CONSTRAINT "PK_e4a77c477e29608e7d17d17fb4f"`);
        await queryRunner.query(`ALTER TABLE "public"."trains" ADD CONSTRAINT "PK_4ef5576fbbbdfcff407d0f3b6ff" PRIMARY KEY ("id", "currenRouteId")`);
        await queryRunner.query(`CREATE INDEX "IDX_0a875e5b908245d08664422ebd" ON "public"."orders" ("assignToTrainCurrenRouteEndlocationid") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ea0868bf622bc7d2ed503eafe" ON "public"."orders" ("assignToTrainCurrenRouteStartlocationid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4e656a1a641ee344881f50885" ON "public"."orders" ("assignToTrainType") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc0d43a83e4083de2db699c644" ON "public"."orders" ("deliveredAtLocationType") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7e11f089a785ffa5f65c9674f" ON "public"."orders" ("pickedUpLocationType") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e1cef4d628456b8e51702fea3" ON "public"."trains" ("currenRouteEndlocationid") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0c6adf735891a8c59a9fec34b" ON "public"."trains" ("currenRouteStartlocationid") `);
        await queryRunner.query(`CREATE INDEX "IDX_99c13262873ed08473e66bc4ea" ON "public"."wagons" ("currentTrainId") `);
        await queryRunner.query(`CREATE INDEX "IDX_16293605f042acb4078c2a324d" ON "public"."packages" ("orderId") `);
        await queryRunner.query(`ALTER TABLE "public"."wagons" ADD CONSTRAINT "FK_99c13262873ed08473e66bc4eac" FOREIGN KEY ("currentTrainId", "currentTrainId") REFERENCES "trains"("id","currenRouteId") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "public"."packages" ADD CONSTRAINT "FK_16293605f042acb4078c2a324d2" FOREIGN KEY ("orderId", "orderId", "orderId", "orderId", "orderId") REFERENCES "orders"("id","pickedUpLocationId","deliveredAtLocationId","assignToTrainId","assignToTrainCurrenRouteId") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
